version: "3.0"

services:
  nginx:
    build:
      context: .
      dockerfile: etc/nginx/Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./src:/var/src/
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: etc/php/Dockerfile
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ./src:/var/src/
